export const jokes = [
  {
    id: 1,
    title: "Bug Magnet",
    content: "Why do programmers hate nature? Too many bugs 🐛😂",
    category: "Programming",
    language: "English",
    author: "Anonymous",
    likes: 210,
    dislikes: 9,
    isFamilyFriendly: true,
    createdAt: "2025-01-01",
    tags: ["bugs", "coding", "developer"]
  },
  {
    id: 2,
    title: "Student Mode",
    content: "My brain during exams: loading… 99%… error 😵‍💫",
    category: "Student Life",
    language: "English",
    author: "College Kid",
    likes: 180,
    dislikes: 6,
    isFamilyFriendly: true,
    createdAt: "2025-01-02",
    tags: ["exam", "study", "college"]
  },
  {
    id: 3,
    title: "WiFi Priority",
    content: "I don’t need a therapist, I just need faster WiFi 📶😄",
    category: "Technology",
    language: "English",
    author: "Netizen",
    likes: 320,
    dislikes: 11,
    isFamilyFriendly: true,
    createdAt: "2025-01-03",
    tags: ["wifi", "internet", "tech"]
  },
  {
    id: 4,
    title: "Lazy Workout",
    content: "I started a 7-day workout plan… still on Day 1 🏋️‍♂️😂",
    category: "Fitness",
    language: "English",
    author: "Gym Ghost",
    likes: 260,
    dislikes: 14,
    isFamilyFriendly: true,
    createdAt: "2025-01-04",
    tags: ["fitness", "lazy", "gym"]
  },
  {
    id: 5,
    title: "Frontend Truth",
    content: "Frontend developers fix bugs by changing colors 🎨🤣",
    category: "Programming",
    language: "English",
    author: "UI Ninja",
    likes: 410,
    dislikes: 18,
    isFamilyFriendly: true,
    createdAt: "2025-01-05",
    tags: ["frontend", "css", "ui"]
  },
  {
    id: 6,
    title: "Alarm Drama",
    content: "My alarm clock and I are in a toxic relationship ⏰😴",
    category: "Daily Life",
    language: "English",
    author: "Sleepy Soul",
    likes: 350,
    dislikes: 10,
    isFamilyFriendly: true,
    createdAt: "2025-01-06",
    tags: ["sleep", "alarm", "morning"]
  },
  {
    id: 7,
    title: "Debugging",
    content: "Debugging is like being a detective in a crime movie where you are the criminal 🕵️‍♂️😂",
    category: "Programming",
    language: "English",
    author: "Coder",
    likes: 520,
    dislikes: 22,
    isFamilyFriendly: true,
    createdAt: "2025-01-07",
    tags: ["debugging", "coding", "developer"]
  },
  {
    id: 8,
    title: "Food Love",
    content: "My favorite exercise is eating 🍕😆",
    category: "Food",
    language: "English",
    author: "Foodie",
    likes: 390,
    dislikes: 17,
    isFamilyFriendly: true,
    createdAt: "2025-01-08",
    tags: ["food", "funny", "lazy"]
  },
  {
    id: 9,
    title: "Meeting Mood",
    content: "This meeting could’ve been an email 📧😐",
    category: "Office",
    language: "English",
    author: "Office Guy",
    likes: 450,
    dislikes: 19,
    isFamilyFriendly: true,
    createdAt: "2025-01-09",
    tags: ["office", "meeting", "work"]
  },
  {
    id: 10,
    title: "Sleep Logic",
    content: "I’m not lazy, I’m on energy-saving mode 🔋😂",
    category: "Daily Life",
    language: "English",
    author: "Power Saver",
    likes: 600,
    dislikes: 30,
    isFamilyFriendly: true,
    createdAt: "2025-01-10",
    tags: ["sleep", "lazy", "life"]
  }
];
